import java.util.Random;
import java.util.Scanner;

public class Mastermind {
    /*
     * Stripped-down single-player clone of Mastermind, the color guessing game.
     * A three-digit sequence is generated by the computer at random.
     * The player has up to 10 tries for guessing the sequence.
     * After each guess, the player is told how many digits were correct.
     * There are 3 colors: red (r), green (g) and blue (b).
     */
    public static void main(String[] args) {
        Random random = new Random();
        Scanner scanner = new Scanner( System.in );

        String colors = "rgb";
        String solution = "";
        for (int i = 0; i < 3; i++) {
            solution = solution + colors.charAt( random.nextInt(3) );
        }

        for (int round = 0; round < 10; round++) {
            System.out.println("Enter guess: ");
            String guess = scanner.nextLine();

            if ( guess.equals(solution) ) {
                System.out.println("That's right! You have won!!");
                return;
            }
            int correct = 0;
            for (int i = 0; i < 3; i++) {
                if (guess.charAt(i) == solution.charAt(i)) {
                    correct = correct + 1;
                }
            }
            System.out.println("Not quite correct. You've got this many spaces right: " + correct);
        }
        System.out.println("Better luck next time! The correct solution was " + solution);
    }
}
